config/routes.rb
ABakersDozen::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/followed_recipes"

  #root :to => 'recipes#index'
  resources :recipes
  root :to => redirect('/recipes')
  get "recipes/new"

  #resources :users
  #GET	/users/1/following	following	following_user_path(1)
  #GET	/users/1/followers	followers	followers_user_path(1)
  resources :users do
    member do
      get :following, :followers
    end
  end
  #root :to => redirect('/users')
  #get "users/new"
  

  match '/signup', to: 'users#new', via: 'get' #gives us signup_path
  match '/home', to: 'recipes#index'

  #signin/signout:
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy'#,     via: 'delete' #commented out to fix heroku

  resources :users, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  #comments don't need a 'new' or 'edit' method:
  resources :comments, only: [:new, :create, :destroy]
end

app/models/comment.rb
#=header
class Comment < ActiveRecord::Base

  #relationships
  belongs_to :user
  belongs_to :recipe

  #validations
  validates :content, presence: true, length: { maximum: 300 }
  validates :rating, presence: true, :numericality => {:greater_than => 0, :less_than => 5}
  validates :user_id, presence: true
  validates :recipe_id, presence: true

  #orders it by creation date with newest first
  default_scope -> { order('created_at DESC') }

  #class methods
  def Comment.all_ratings
    all_ratings = {"Icky" => 1, "All right" => 2, "Good" => 3, "Delicious!" => 4}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
#*** really only need pages for create and destroy. also index.
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    if params[:recipe] != nil
      @recipe = Recipe.find(params[:recipe].to_i)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.recipe_id = params[:recipe_id].to_i
    @comment.user_id = params[:user_id].to_i
    @recipe = Recipe.find(@comment.recipe_id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @recipe, notice: 'Comment was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end



  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :ok }
    end
  end

  private

    def comments_params
      params.require(:comment).permit(:content)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @comment = Comment.find(params[:id])
      @user = User.find(@comment.user_id)
      redirect_to(recipes_path) unless current_user?(@user)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
Posted by <b><%= link_to comment.user.name, comment.user %></b> on <%= comment.created_at.strftime("%m/%d/%Y") %>: <br>
<b>Rating:</b> <%= comment.rating %><p>
<%= comment.content %>
<p><HR WIDTH="50%" align="left" SIZE="1" NOSHADE><p>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# deleted user_id field, grab from session %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 5 %>
  </div>

  <div class="field">
    <%#= f.label :rating %><br />
    <%#= f.number_field :rating %>
    <%= f.label :rating %>
    <% Comment.all_ratings.each do |rating| %>
      <br><%= f.radio_button :rating, rating[1], id: rating[0] %>
      <%= rating[0].humanize %>
    <% end %>
  </div>

    <%= hidden_field_tag :user_id, current_user.id %>
    <%= hidden_field_tag :recipe_id, params[:recipe] %>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_id %></td>
    <td><%= comment.content %></td>
    <td><%= comment.rating %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>Rate and Comment on <%= @recipe.name %>!</h1><p>

<%= render 'form' %>

<%= link_to 'Back', @recipe %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Rating:</b>
  <%= @comment.rating %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>