config/routes.rb
ABakersDozen::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/followed_recipes"

  #root :to => 'recipes#index'
  resources :recipes
  root :to => redirect('/recipes')
  get "recipes/new"

  #resources :users
  #GET	/users/1/following	following	following_user_path(1)
  #GET	/users/1/followers	followers	followers_user_path(1)
  resources :users do
    member do
      get :following, :followers
    end
  end
  #root :to => redirect('/users')
  #get "users/new"
  

  match '/signup', to: 'users#new', via: 'get' #gives us signup_path
  match '/home', to: 'recipes#index'

  #signin/signout:
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy'#,     via: 'delete' #commented out to fix heroku

  resources :users, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  #comments don't need a 'new' or 'edit' method:
  resources :comments, only: [:new, :create, :destroy]
end

app/models/recipe.rb
#=Recipe:
#* name
#* description
#* picture
#* ingredients
#* instructions

class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy #if recipe is deleted, then the comments are deleted
  validates :name, presence: true, length: { maximum: 50 }

   #class methods:
   def self.search(search_query)
     find(:all, :conditions => ['name LIKE ?', "%#{search_query}%"])
   end

   #instance methods:
   def average_rating
     av = 0
     n = 0
     self.comments.each do |comment|
       rating = comment.rating
       av = av + rating
       n = n + 1
     end
     av/n
   end

  #the feed:
  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids
    where("user_id IN (?) OR user_id = ?", followed_user_ids, user)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :signed_in_user, only: [:create, :update, :edit, :destroy]
  before_filter :correct_user,   only: [:update, :edit, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    if :search_query
      @recipes = Recipe.search(params[:search_query])
      @recipes = @recipes.sort!{ |x, y| x["created_at"] <=> y["created_at"] }.reverse
    else     
      @recipes = Recipe.find(:all, :order => 'recipes.created_at').reverse
    end
    #@recipes.created_at.strftime("%s").to_i)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/followed_recipes
  # GET /recipes/followed_recipes.json
  def followed_recipes
    #if :search_query
    #  @recipes = Recipe.search(params[:search_query])
    #  @recipes = @recipes.sort!{ |x, y| x["created_at"] <=> y["created_at"] }.reverse
    #else     
    if signed_in?
      current_user.followers.each do |following|
        @recipes = Recipe.find(:all, :user_id => following, :order => 'recipes.created_at').reverse
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @owner = @recipe.user
    @ingredients = @recipe.ingredients.split("\n")
    @instructions = @recipe.instructions.split("\n")
    @date = @recipe.created_at.strftime("%m/%d/%Y")
    #find all comments associated with recipe
    @comments = @recipe.comments.paginate(page: params[:page])
    @chefcertified = false
    @comments.each do |comment|
      if (comment.rating == 4 && comment.user.chef)
         @chefcertified = true
      end
    end
    if @owner.chef
       @chefcertified = true
    end
    #debugger
    #@comments = Comment.find(:all, :recipe_id => @recipe.id)
    #@comments = @recipe.comments.paginate(page: params[:page])
    #    Micropost.where("user_id = ?", id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    #@recipe.user_id = params[:user_id].to_i
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  #changed redirect to go to home page
  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.user_id = params[:user_id].to_i

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :ok }
    end
  end

  private
    #def correct_user
    #  @recipe = current_user.recipes.find_by(id: params[:id])
    #  redirect_to root_url if @recipe.nil?
    #end
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @recipe = Recipe.find(params[:id])
      @user = User.find(@recipe.user_id)
      redirect_to(recipes_path) unless current_user?(@user)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br />
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/followed_recipes.html.erb
<h1>My Followed Recipes</h1>
  <% if signed_in? %>
    <% if curent_user.recipes.any? %>
      <% @recipes.each do |recipe| %>
        <%= image_tag(recipe.picture, :size => "130x130", :hspace => '15px', :vspace => '5px', :align => "left") %>
        <b><%= link_to recipe.name, recipe %></b><br><br>
        <% if recipe.user != nil %>
          Submitted by <%= link_to recipe.user.name, recipe.user %><br>
        <% end %>
        Submitted on <%= recipe.created_at.strftime("%m/%d/%Y") %><br><br>
        <b>Description:</b><br>
        <%= recipe.description %><br><br>
        <HR WIDTH="50%" align="left" SIZE="3" NOSHADE><br>
      <% end %>
    <% else %>
      Go <%= link_to 'find', recipes_path %> some recipes!
    <% end %>
  <% else %>
    Please <%= link_to 'sign-in', signin_path %> to follow recipes.
  <% end %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
  <% if signed_in? %>
    <%= link_to 'Post New Recipe', new_recipe_path %><br>
  <% else %>
    Please <%= link_to 'sign-in', signin_path %> to post a recipe.
  <% end %>
<HR WIDTH="70%" align="left" SIZE="3" NOSHADE><br>

<% @recipes.each do |recipe| %>
   <% if recipe.picture != nil %>
     <%= image_tag(recipe.picture, :size => "130x130", :hspace => '15px', :vspace => '5px', :align => "left") %>
   <% end %>
   <b><%= link_to recipe.name, recipe %></b><br><br>
  <% if recipe.user != nil %>
   Submitted by <%= link_to recipe.user.name, recipe.user %><br>
  <% end %>
   Submitted on <%= recipe.created_at.strftime("%m/%d/%Y") %><br><br>
   <b>Description:</b><br>
   <%= recipe.description %><br><br>
   <HR WIDTH="50%" align="left" SIZE="3" NOSHADE><br>
<% end %>

app/views/recipes/index.html.haml
-#commented and pasted for now
-#  This file is app/views/recipes/index.html.haml
%h1 All Recipes

= form_tag movies_path, :method => :get, :id => 'ratings_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":release_date_sort", true if @date_header
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @selected_ratings.include?(rating), :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => 'ratings_submit'

%table#movies
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Movie Title', movies_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      %th Rating
      %th{:class => @date_header}= link_to 'Release Date', movies_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/new.html.haml
%h1 Create New Recipe

= form_tag recipes_path do

  = label :recipe, :title, 'Title'
  = text_field :recipe, 'title'

  = label :recipe, :description, 'Short Description'
  = text_box :recipe, 'description'

  = label :recipe, :pic, 'Picture'
  = text_field :recipe, 'picture'

  = label :recipe, :ingredients, 'Ingredients:'
  = text_box :recipe, 'ingredients, split apart by newlines'

  = label :recipe, :instructions, 'Cooking Instructions'
  = text_box :recipe, 'instructions'

  = submit_tag 'Save Changes'

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<%= image_tag(@recipe.picture, :size => "250x250", :hspace => '15px', :vspace => '15px', :align => "left") %>

<p>
  <% if @recipe.user != nil %>
   Submitted by <%= link_to @recipe.user.name, @recipe.user %><br>
  <% end %>
</p>

<p>
Average Rating: 
    <% if @recipe.comments.any? %>
      <%= @recipe.average_rating %>
    <% else %>
      N/A
    <% end %>
    <% if @chefcertified %>
      <%= image_tag('chefcertified.png',:hspace => '2px', :vspace => '2px', :align => "left") %>
    <% end %>
</p>

<p>
   <b>Description:</b><br>
   <%= @recipe.description %>
</p>

<p><br><br>
   <b>Ingredients:</b><br>
   <% @ingredients.each do |ingredient| %>
     <%= ingredient %><br>
   <% end %>
</p>

<p>
  <b>Instructions:</b><p>
   <% @instructions.each do |step| %>
     <%= step %><p>
   <% end %>
</p>
<p><HR WIDTH="50%" align="left" SIZE="3" NOSHADE><p>

<b>Comments and Ratings:</b><p>
  <% if signed_in? %>
    <%= link_to 'Add new comment', new_comment_path(:recipe => @recipe) %> <p>
  <% else %>
    Please <%= link_to 'sign-in', signin_path %> to comment.
  <% end %>
<p>

    <% if @recipe.comments.any? %>
      <%= render @comments %>
      <%= will_paginate @comments %>
    <% end %>

<% 
=begin %>
  <% @comments.each do |comment| %>
    Posted by <b><%#= comment.user_id.username %></b> on <%= comment.created_at %>: <br>
    <b>Rating:</b> <%= comment.rating %><p>
    <%= comment.content %>
  <p><HR WIDTH="50%" align="left" SIZE="1" NOSHADE><p>
  <% end %>
<% 
=end %>

<p><HR WIDTH="80%" align="left" SIZE="3" NOSHADE><p>

<% if @recipe.user == current_user %>
  <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
  <%= link_to 'Delete', @recipe, confirm: 'Are you sure?',method: :delete %> |
<% end %>
<%= link_to 'Back', recipes_path %>