config/routes.rb
ABakersDozen::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/followed_recipes"

  #root :to => 'recipes#index'
  resources :recipes
  root :to => redirect('/recipes')
  get "recipes/new"

  #resources :users
  #GET	/users/1/following	following	following_user_path(1)
  #GET	/users/1/followers	followers	followers_user_path(1)
  resources :users do
    member do
      get :following, :followers
    end
  end
  #root :to => redirect('/users')
  #get "users/new"
  

  match '/signup', to: 'users#new', via: 'get' #gives us signup_path
  match '/home', to: 'recipes#index'

  #signin/signout:
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy'#,     via: 'delete' #commented out to fix heroku

  resources :users, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  #comments don't need a 'new' or 'edit' method:
  resources :comments, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
#    attr_accessor :username, :name, :password

#    def initialize(attributes = {})
#      @username = attributes[:username]
#      @name = attributes[:name]
#      @password = attributes[:password]
#    end

#def initialize(user)
#  @picture = "/assets/defaultprofile.png"
#end

#def image
#  @user = User.find()
#  if @user.picture.empty?
#    "/assets/defaultprofile.png"
#  else
#    @user.picture
#  end
#end

#relationships:
  #destroys comments if user is destroyed:
  has_many :comments, dependent: :destroy 
  has_many :recipes
#followers:
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship", #not its own class
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

#6.3.2: password and password_confirmation attributes: these virtual attributes are implemented automatically by has_secure_password.
  has_secure_password

#required validations:
  validates :username, presence: true, length: { maximum: 25 },     		uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 4 }
  #picture and interests are not required to sign up.
  #picture does need to be of the form *.png, jpg, etc. though.
  #VALID_PIC_REGEX = /\A[\w+\-.]+\.[jpg, jpeg, png]\z/i
  #validates :picture, format: {with: VALID_PIC_REGEX}

#ensure username uniqueness by downcasing:
  before_save { self.username = username.downcase }

#to remeber a log-in:
  before_create :create_remember_token

#remember log-in class methods:
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

#section 11: following others
  def following?(other_user)
    #relationships.find_by(followed_id: other_user.id) #in ruby 4.0
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
    #***used to be 'destroy!'
  end

  def feed
    Recipe.from_users_followed_by(self)
  end
  ############################################################
  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

#    t.string   "username"
#    t.string   "name"
#    t.string   "picture"
#    t.text     "interests"
#    t.datetime "created_at"
#    t.datetime "updated_at"

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :destroy, :following, :followers]
  before_filter :correct_user,   only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    if @user.picture == nil
      @user.picture = "defaultprofile.png"
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  #-------------------------------------------------

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.picture == nil
      @user.picture = "defaultprofile.png"
    end
    respond_to do |format|
      if @user.save
        sign_in @user #when they sign up, sign them in
        flash[:success] = "Welcome to A Baker's Dozen!"
        format.html { redirect_to @user, notice: "Welcome to A Baker's Dozen, "+@user.name+"!" }
        format.json { render json: @user, status: :created, location: @user }
      else #sign-up failure
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.picture == nil
      @user.picture = "defaultprofile.png"
    end
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Information updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
#-------------------------------------------
  def following
    @title = "Following" #page title
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

#--------------------------------------------
  private
    def user_params
      params.require(:user).permit(:name, :username, :password,
                                   :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(recipes_path) unless current_user?(@user)
    end
end



#user = User.find_by(email: email)
#current_user = user.authenticate(password): returns user or false

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :picture %>
    <%= f.text_field :picture %>

    <%= f.label :interests %>
    <%= f.text_area :interests, :rows => 3 %>

    <%= f.label :password, "Current or New Password" %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

  <div class="actions">
    <%= f.submit "Update Information", class: "btn btn-large btn-primary"  %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :picture %>
    <%= f.text_field :picture %>

    <%= f.label :interests %>
    <%= f.text_area :interests, :rows => 3 %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.label :chef, "Are you a Chef? (check box if yes)" %>
    <%= f.check_box :chef %>

  <div class="actions">
    <%= f.submit "Create my account", class: "btn btn-large btn-primary"  %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Name</th>
    <th>Picture</th>
    <th>Interests</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.name %></td>
    <td><%= user.picture %></td>
    <td><%= user.interests %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class="row">
  <div class="span6 offset3">
<%= render 'form' %>
</div>
</div>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<div class="row">
  <aside class="span4">

<%= image_tag(@user.picture, :size => "250x250", :hspace => '15px', :vspace => '15px', :align => "left") %>
    <% if @user.chef %>
      <%= image_tag('chefcertified.png',:hspace => '200px', :vspace => '2px', :align => "right") %>
    <% end %>

<p>

<b>Name: </b><%= @user.name %><br>
<b>Interests: </b><%= @user.interests %><br>
<b><%= @user.username %>'s Recipes: </b></br>

<p><HR WIDTH="50%" align="left" SIZE="3" NOSHADE><p>
<% @user.recipes.each do |recipe| %>
   <%= image_tag(recipe.picture, :size => "100x100", :hspace => '15px', :vspace => '5px', :align => "left") %>
   <b><%= link_to recipe.name, recipe %></b><br>
   Submitted on <%= recipe.created_at.strftime("%m/%d/%Y") %><br><br>
   <b>Description:</b><br>
   <%= recipe.description %><br><br>
<% if @user == current_user %>
   <%= link_to 'Edit', edit_recipe_path(recipe) %>
   <%= link_to 'Destroy', recipe, confirm: 'Are you sure?',method: :delete %><br>
<% end %>
   <HR WIDTH="30%" align="left" SIZE="1" NOSHADE><br>
<% end %>

    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if signed_in? %>
  </div>
</div>

<p>   <HR WIDTH="30%" align="left" SIZE="1" NOSHADE><p>
<% if @user == current_user %>
  <%= link_to 'Edit my information', edit_user_path(@user) %>
<% end %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">

    <section>
      <h1><%= @user.name %>'s Followers</h1>
    </section>

    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to image_tag('defaultprofile.png', :size => "30x30"), user %>
            <%# instead of user.picture, do defaultprofile.jpg for now %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>

<HR WIDTH="50%" align="left" SIZE="3" NOSHADE><br>
<h1><%= @user.name %>'s Followed Recipes</h1><p>

  <div class="span8">
    <h3><%#= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <% @user.followed_users.each do |followed_user| %>
          <% followed_user.recipes.each do |recipe| %>
            <%#= render recipe %>
               <%= image_tag(recipe.picture, :size => "130x130", :hspace => '15px', :vspace => '5px', :align => "left") %>
   		<b><%= link_to recipe.name, recipe %></b><br><br>
  		<% if recipe.user != nil %>
  		 Submitted by <%= link_to recipe.user.name, recipe.user %><br>
  		<% end %>
  		 Submitted on <%= recipe.created_at.strftime("%m/%d/%Y") %><br><br>
  		 <b>Description:</b><br>
   		<%= recipe.description %><br><br>
   		<HR WIDTH="50%" align="left" SIZE="3" NOSHADE><br>
          <% end %>
        <% end %>
        <%#= RENDER RECIPES FOLLOWED HERE %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>