config/routes.rb
ABakersDozen::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/followed_recipes"

  #root :to => 'recipes#index'
  resources :recipes
  root :to => redirect('/recipes')
  get "recipes/new"

  #resources :users
  #GET	/users/1/following	following	following_user_path(1)
  #GET	/users/1/followers	followers	followers_user_path(1)
  resources :users do
    member do
      get :following, :followers
    end
  end
  #root :to => redirect('/users')
  #get "users/new"
  

  match '/signup', to: 'users#new', via: 'get' #gives us signup_path
  match '/home', to: 'recipes#index'

  #signin/signout:
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy'#,     via: 'delete' #commented out to fix heroku

  resources :users, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  #comments don't need a 'new' or 'edit' method:
  resources :comments, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title A Baker's Dozen
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title A Baker's Dozen
    %h1.subtitle
      A social recipe-sharing site
      %right
        - if signed_in?
          = link_to 'Profile', current_user
          |
          = link_to 'Log-out', signout_path, :method => :delete
        - else
          = link_to 'Log-in', signin_path
    %nav 
      = link_to 'Home', recipes_path
      - if signed_in?
        |
        = link_to 'Followed Recipes', following_user_path(current_user)
      %right
        = form_tag recipes_path, :action => 'search', :method => :get do
          = text_field_tag :search_query, params[:search_query], :placeholder => "Search Recipes"
          = submit_tag 'Go!', :id => 'search_submit'

    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield